#!/usr/bin/env bash
# Continue the sealed non-M3 protocol after Stage-1 has created candidates.
# Every command below uses only outer-train inner-CV data until the explicit
# locked outer-confirmation program is reached.
set -euo pipefail

ROOT="/home/puzexuan/study/code/blology_prediction/service"
PYTHON="/home/puzexuan/anaconda3/envs/biology_prediction_gpu/bin/python"
OUTPUT="$ROOT/results/hybrid_embedding_tree_exp"

candidate_rows=$(awk 'END { print NR - 1 }' "$OUTPUT/stage1/selected_candidates.csv")
if (( candidate_rows == 0 )); then
    "$PYTHON" "$ROOT/scripts/diagnostics/finalize_hybrid_early_stop.py"
    exit 0
fi

# The same non-M3 tree-only reference grid is needed on fold 1 for the Stage-2
# development gate.  No M3 result is read or generated by this script.
"$PYTHON" "$ROOT/scripts/diagnostics/run_hybrid_embedding_tree_stage.py" \
    --stage stage2 --fold 1 --families A1,A2,A3,A4 --models M0,M1,M2,M4,M5,M6 \
    --tag f1_tree_reference_nonm3 --tree-n-jobs 1

# Candidates retain their target/family/model identity from Stage 1.  The
# runner repeats their predeclared hyperparameter grid inside fold-1 inner CV.
"$PYTHON" "$ROOT/scripts/diagnostics/run_hybrid_embedding_tree_stage.py" \
    --stage stage2 --fold 1 --families A1 --models M0 --pipeline-spec "$OUTPUT/stage1/selected_candidates.csv" \
    --tag f1_stage1_candidates_nonm3 --tree-n-jobs 1

"$PYTHON" "$ROOT/scripts/diagnostics/consolidate_hybrid_execution_manifest.py"
"$PYTHON" "$ROOT/scripts/diagnostics/confirm_hybrid_embedding_tree_stage2.py"

stage2_status=$("$PYTHON" -c "import json; print(json.load(open('$OUTPUT/stage2/locked_pipeline.json'))['status'])")
if [[ "$stage2_status" == "READY_FOR_UNTOUCHED_CONFIRMATION" ]]; then
    "$PYTHON" "$ROOT/scripts/diagnostics/evaluate_locked_hybrid_outer.py" --tree-n-jobs 1 --bootstrap-repeats 10000
    printf 'STAGE2_LOCKED_OUTER_CONFIRMATION_FINISHED\n'
else
    "$PYTHON" "$ROOT/scripts/diagnostics/finalize_hybrid_stage2_stop.py"
    printf 'STAGE2_DEVELOPMENT_STOP_FINISHED\n'
fi
